settings:
  #username: "Readme-Workflows" # Replace with your username or comment out this line
  #commit_msg: ":zap: Update README with the recent activity"
  max_lines: 5
  readme_file: "./README.md"
  disabled_events:
    - "comments"
    - "member"
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT+00:00"
    text: "Last Updated: {DATE}"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
  #commit_name: "readme-bot"
  #commit_email: "41898282+github-actions[bot]@users.noreply.github.com"
  line_prefix: "> "
  #ignored_repos:
    #- username/repo
messages:
  comments: "ğŸ’¬ Commented on {ID} in {REPO}"
  push: "âœˆï¸ Pushed {AMOUNT} commit(s) to {REPO}"
  issue_opened: "â—ï¸ Opened issue {ID} in {REPO}"
  issue_closed: "ğŸ§¯ Closed issue {ID} in {REPO}"
  pr_opened: "ğŸ˜° Opened PR {ID} in {REPO}"
  pr_closed: "ğŸ†˜ Closed PR {ID} in {REPO}"
  pr_merged: "ğŸ‰ Merged PR {ID} in {REPO}"
  create_repo: "ğŸ’¾ Created new repository {REPO}"
  fork_repo: "ğŸ”± Forked {FORK} from {REPO}"
  wiki_create: "ğŸ“– Created new wiki page {WIKI} in {REPO}"
  added_member: "ğŸ¤ Became collaborator on {REPO}"
  changes_approved: "ğŸ‘ Approved {ID} in {REPO}"
  changes_requested: "âš ï¸ Requested changes in {ID} in {REPO}"
  new_release: "ğŸ”¨ Released {ID} in {REPO}"
  new_star: "â­ Starred {REPO}"
